import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./providers";
import { ScreenPreferencesProvider } from "./context/ScreenPreferencesContext";
import DynamicLayout from "@/components/client/dynamicForm/DynamicLayout";
import MainContainer from "@/components/client/server/MainContainer";

export const metadata: Metadata = {
  title: "Admin APP",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <Providers>
          <ScreenPreferencesProvider>
            <div className="flex">
              <DynamicLayout />
              <MainContainer>
                {children}
              </MainContainer>
            </div>
          </ScreenPreferencesProvider>
        </Providers>
      </body>
    </html>
  );
}

