import type { Metadata } from "next";
import "./globals.css";
import DynamicLayout from "@/components/client/dynamicForm/DynamicLayout";
import MainContainer from "@/components/client/server/MainContainer";
import ReduxProvider from "@/Store/ReduxProvider";
import { GlobalPreferencesProvider } from "./context/GlobalPreferencesContext";

export const metadata: Metadata = {
  title: "Admin APP",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <ReduxProvider>
          <GlobalPreferencesProvider>
            <div className="flex">
              <DynamicLayout />
              <MainContainer>
                {children}
              </MainContainer>
            </div>
          </GlobalPreferencesProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}

